export const OlOpType = {
  INDENT: 'OL_INDENT',
  OUTDENT: 'OL_OUTDENT',
  SELECT_WITH_MOUSE_MOVE: 'OL_SELECT_WITH_MOUSE_MOVE',
  PASTE_AND_SPLIT_BY_LINE_BREAK: 'PASTE_AND_SPLIT_BY_LINE_BREAK',
  MOVE_FOCUS: 'OL_MOVE_FOCUS',
};
