export const EXT_DATA_KEY_IMAGES = "EXT_DATA_KEY_IMAGES";


export const OP_TYPE_ADD_IMAGE = 'OP_TYPE_ADD_IMAGE';
export const OP_TYPE_ADD_TOPIC_IMAGE = 'OP_TYPE_ADD_TOPIC_IMAGE';
export const OP_TYPE_DELETE_TOPIC_IMAGE = 'OP_TYPE_DELETE_TOPIC_IMAGE';
export const OP_TYPE_SET_TOPIC_IMAGE = 'OP_TYPE_SET_TOPIC_IMAGE';
export const OP_TYPE_MOVE_TOPIC_IMAGE = 'OP_TYPE_MOVE_TOPIC_IMAGE';
