export const IpcChannelName = {
  RM_GET_I18N: 'RM_GET_I18N',

  RM_NEW_FILE: 'RM_NEW_FILE',
  RM_SAVE: "RM_SAVE",
  RM_SAVE_SYNC: "RM_SAVE_SYNC",
  RM_GET_FILE_CONTENT: 'RM_GET_FILE_CONTENT',
  RM_GET_STORE_ITEM: 'RM_GET_STORE_ITEM',
  RM_SET_STORE_ITEM: 'RM_SET_STORE_ITEM',
  RM_GET_FONT_LIST: 'RM_GET_FONT_LIST',
  RM_OPEN_FILE: 'RM_OPEN_FILE',
  // RM_SAVE_ALL_FILES_OF_WINDOW: "RM_SAVE_ALL_FILES_OF_WINDOW",

  MR_FILE_WINDOW: 'MR_FILE_WINDOW',
  MR_GLOBAL: 'MR_GLOBAL',
};

export const MrGlobalType = {
  SET_LANG: 'SET_LANG',
  SET_APPEARANCE: 'SET_APPEARANCE',
};

export const IpcType = {
  MR_SAVE: 'MR_SAVE',
  MR_UNDO: 'MR_UNDO',
  MR_REDO: 'MR_REDO',
  MR_BEFORE_CLOSE_WINDOW: 'MR_BEFORE_CLOSE_WINDOW',

};
