export const IpcChannelName = {
  GET_I18N: 'GET_I18N',
  GET_INITIAL_TRANSLATIONS : 'GET_INITIAL_TRANSLATIONS',
  I18N_LANG_CHANGED: 'I18N_LANG_CHANGED',
  I18N_CHANGE_LANG: 'I18N_CHANGE_LANG',
  RM_NEW_FILE: 'NEW_FILE',
  RM_SAVE: "RM_SAVE",
  RM_SAVE_SYNC: "RM_SAVE_SYNC",
  RM_GET_FILE_CONTENT: 'RM_GET_FILE_CONTENT',
  RM_OPEN_FILE: 'RM_OPEN_FILE',
  // RM_SAVE_ALL_FILES_OF_WINDOW: "RM_SAVE_ALL_FILES_OF_WINDOW",

  MR_SAVE: 'MR_SAVE',
  MR_BEFORE_CLOSE_WINDOW: 'MR_BEFORE_CLOSE_WINDOW',
};
