export const I18nTextKey = {

  LANGUAGE: 'LANGUAGE',
  CHINESE_SIMPLIFIED: 'CHINESE_SIMPLIFIED',
  ENGLISH: "ENGLISH",

  CANCEL: 'CANCEL',
  WELCOME_PAGE_TITLE: 'WELCOME_PAGE_TITLE',
  FILE: 'FILE',
  OPEN_FILE: 'OPEN_FILE',
  SAVE: 'SAVE',
  EDITED: 'EDITED',
  DONT_SAVE: 'DONT_SAVE',
  SAVE_AS: 'SAVE_AS',
  NEW_FILE: 'NEW_FILE',
  /*==============================================*/
  EDIT: 'EDIT',
  UNDO: 'UNDO',
  REDO: 'REDO',
  SELECT_ALL: 'SELECT_ALL',
  CUT: 'CUT',
  COPY: 'COPY',
  PASTE: 'PASTE',
  DUPLICATE: 'DUPLICATE',

  PREFERENCES: 'PREFERENCES',
  APPEARANCE: 'APPEARANCE',
  LIGHT: 'LIGHT',
  DARK: 'DARK',
  DISPLAY_LANGUAGE: 'DISPLAY_LANGUAGE',

  /*==============================================*/
  NEW_TAB: 'NEW_TAB',
  UNTITLED: 'UNTITLED',
  SAVE_TIP_TITLE: 'SAVE_TIP_TITLE',
  SAVE_TIP_CONTENT: 'SAVE_TIP_CONTENT',

  SUBSCRIBE: 'SUBSCRIBE',
  FEATURE_LOCK_TIP1: 'FEATURE_LOCK_TIP1',
  FEATURE_LOCK_TIP2: 'FEATURE_LOCK_TIP2',
  FEATURE_ADD_IMAGE_LOCK_TIP: 'FEATURE_ADD_IMAGE_LOCK_TIP',

  LOGIN: 'LOGIN',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  LOGIN_ERROR_TIP: 'LOGIN_ERROR_TIP',
  NOT_HAVE_ACCOUNT: 'NOT_HAVE_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
};
