export const I18nTextKey = {

  LANGUAGE: 'LANGUAGE',
  CHINESE_SIMPLIFIED: 'CHINESE_SIMPLIFIED',
  ENGLISH: "ENGLISH",

  CANCEL: 'CANCEL',
  WELCOME_PAGE_TITLE: 'WELCOME_PAGE_TITLE',
  FILE: 'FILE',
  OPEN_FILE: 'OPEN_FILE',
  SAVE: 'SAVE',
  EDITED: 'EDITED',
  DONT_SAVE: 'DONT_SAVE',
  SAVE_AS: 'SAVE_AS',
  NEW_FILE: 'NEW_FILE',
  /*==============================================*/
  EDIT: 'EDIT',
  UNDO: 'UNDO',
  REDO: 'REDO',
  SELECT_ALL: 'SELECT_ALL',
  CUT: 'CUT',
  COPY: 'COPY',
  PASTE: 'PASTE',
  DUPLICATE: 'DUPLICATE',

  PREFERENCES: 'PREFERENCES',
  APPEARANCE: 'APPEARANCE',
  LIGHT: 'LIGHT',
  DARK: 'DARK',
  DISPLAY_LANGUAGE: 'DISPLAY_LANGUAGE',

  /*==============================================*/
  NEW_TAB: 'NEW_TAB',
  UNTITLED: 'UNTITLED',
  SAVE_TIP_TITLE: 'SAVE_TIP_TITLE',
  SAVE_TIP_CONTENT: 'SAVE_TIP_CONTENT',


};
